name: PDF To Markdown workflow
description: Updates README.md generating PDF images
author: northy

inputs:
  pdf_input:
    description: 'Input PDF file'
    required: true
  root_folder:
    description: "Root output folder"
    default: ''
    required: false
  output_folder:
    description: 'Output pngs folder'
    default: 'output_pngs'
    required: false
  source_md:
    description: "Source markdown file"
    required: true
  output_md:
    description: "Output markdown file"
    default: 'README.md'
    required: false
  line_end:
    description: "Line end"
    default: '---\n'
    required: false

branding:
  icon: 'activity'
  color: 'yellow'

runs:
  using: 'node12'
  main: 'run.js'